### PR TITLE
add ci/build

### PR DESCRIPTION
**Pull request by dustylink**

### CODE REVIEW

**Comment by pv93** [comment]
might it be a better strategy to have this script take params that tell it where to go? i.e 
```
ci/build --registry ecr --repository 584250103954.dkr.ecr.us-east-1...
ci/bulid --registry gcr --repository us.gcr.io...
ci/build --registry docker --repository docker.io/draft/...
```

Will be better for extensibility, and could even make it a script in gcloud that we can call from other repos using submodules.

This looks good for now though, the above might be something to consider for the Later column.

**Comment by dustylink** [comment]
@pv93 yup agreed. i actually stripped it of that functionality for the reason you mention.  in this incarnation these are single fire and might as well be kept simple. they'll never be invoked with params until moved to a more general location.

**Comment by ecv** [comment]
yes, pavel is seeing the future correctly, but we don't have that problem yet, so no fix for it yet in master

**Review by ecv — APPROVED** [review]
:horse:

**Pull request merged**
